
[sncast.James]
account = "James"
accounts-file = "/home/jameswasonga/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"




[sncast.default]
account = "Wasonga"
accounts-file = "/home/jameswasonga/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"
